In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Bag of Words BoW

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Create a CountVectorizer instance
vectorizer = CountVectorizer()

# Fit and transform the sentences to create the BOW representation
X = vectorizer.fit_transform(sentences)

# Convert the BOW representation to an array
bow_array = X.toarray()

# Get the feature names (vocabulary)
feature_names = vectorizer.get_feature_names_out()

# Display the results
print("Feature Names (Vocabulary):")
print(feature_names)
print("\nBag of Words Representation:")
print(bow_array)


Feature Names (Vocabulary):
['and' 'animals' 'are' 'at' 'barked' 'cat' 'cats' 'dog' 'dogs' 'great'
 'love' 'loyal' 'mat' 'my' 'on' 'pets' 'sat' 'the']

Bag of Words Representation:
[[0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 2]
 [0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 2]
 [1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]]


# Term Frequency-Inverse Document Frequency (TF-IDF)

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Create a TfidfVectorizer instance
vectorizer = TfidfVectorizer()

# Fit and transform the sentences to create the TF-IDF representation
X = vectorizer.fit_transform(sentences)

# Convert the TF-IDF representation to an array
tfidf_array = X.toarray()

# Get the feature names (vocabulary)
feature_names = vectorizer.get_feature_names_out()

# Display the results
print("Feature Names (Vocabulary):")
print(feature_names)
print("\nTF-IDF Representation:")
print(tfidf_array)


Feature Names (Vocabulary):
['and' 'animals' 'are' 'at' 'barked' 'cat' 'cats' 'dog' 'dogs' 'great'
 'love' 'loyal' 'mat' 'my' 'on' 'pets' 'sat' 'the']

TF-IDF Representation:
[[0.         0.         0.         0.         0.         0.27222751
  0.         0.         0.         0.         0.         0.
  0.40648465 0.         0.40648465 0.         0.40648465 0.65589852]
 [0.         0.         0.         0.40648465 0.40648465 0.27222751
  0.         0.40648465 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.65589852]
 [0.43429718 0.         0.35038823 0.         0.         0.
  0.43429718 0.         0.35038823 0.43429718 0.         0.
  0.         0.         0.         0.43429718 0.         0.        ]
 [0.         0.         0.         0.         0.         0.42799292
  0.         0.         0.         0.         0.63907044 0.
  0.         0.63907044 0.         0.         0.         0.        ]
 [0.         0.55032913 0.44400208 0.        

# Bigrams + TFIDF 

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TfidfVectorizer instance for bigrams
vectorizer_tfidf = TfidfVectorizer(ngram_range=(2, 2))

# Fit and transform the sentences to create the TF-IDF representation for bigrams
X_tfidf = vectorizer_tfidf.fit_transform(sentences)

# Convert the TF-IDF representation to an array
tfidf_array_bigrams = X_tfidf.toarray()

# Get the feature names (bigrams)
feature_names_tfidf_bigrams = vectorizer_tfidf.get_feature_names_out()

# Display the results
print("Feature Names (Bigrams):")
print(feature_names_tfidf_bigrams)
print("\nTF-IDF Representation (Bigrams):")
print(tfidf_array_bigrams)


Feature Names (Bigrams):
['and dogs' 'are great' 'are loyal' 'at the' 'barked at' 'cat sat'
 'cats and' 'dog barked' 'dogs are' 'great pets' 'love my' 'loyal animals'
 'my cat' 'on the' 'sat on' 'the cat' 'the dog' 'the mat']

TF-IDF Representation (Bigrams):
[[0.         0.         0.         0.         0.         0.46369322
  0.         0.         0.         0.         0.         0.
  0.         0.46369322 0.46369322 0.37410477 0.         0.46369322]
 [0.         0.         0.         0.46369322 0.46369322 0.
  0.         0.46369322 0.         0.         0.         0.
  0.         0.         0.         0.37410477 0.46369322 0.        ]
 [0.46369322 0.46369322 0.         0.         0.         0.
  0.46369322 0.         0.37410477 0.46369322 0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.70710678 0.
  0.70710678 0.         0.         0.        

# BoW of Unigrams + Bigrams 

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Create a CountVectorizer instance for unigrams and bigrams
vectorizer_bow = CountVectorizer(ngram_range=(1, 2))

# Fit and transform the sentences to create the BOW representation for unigrams and bigrams
X_bow = vectorizer_bow.fit_transform(sentences)

# Convert the BOW representation to an array
bow_array_bigrams = X_bow.toarray()

# Get the feature names (unigrams and bigrams)
feature_names_bigrams = vectorizer_bow.get_feature_names_out()

# Display the results
print("Feature Names (Unigrams and Bigrams):")
print(feature_names_bigrams)
print("\nBag of Words Representation (Unigrams and Bigrams):")
print(bow_array_bigrams)


Feature Names (Unigrams and Bigrams):
['and' 'and dogs' 'animals' 'are' 'are great' 'are loyal' 'at' 'at the'
 'barked' 'barked at' 'cat' 'cat sat' 'cats' 'cats and' 'dog' 'dog barked'
 'dogs' 'dogs are' 'great' 'great pets' 'love' 'love my' 'loyal'
 'loyal animals' 'mat' 'my' 'my cat' 'on' 'on the' 'pets' 'sat' 'sat on'
 'the' 'the cat' 'the dog' 'the mat']

Bag of Words Representation (Unigrams and Bigrams):
[[0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 2 1 0 1]
 [0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 1 1 0]
 [1 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]]


# 1gram + 2grams + 3grams 

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Create a CountVectorizer instance for unigrams and bigrams
vectorizer_bow = CountVectorizer(ngram_range=(1, 3))

# Fit and transform the sentences to create the BOW representation for unigrams and bigrams
X_bow = vectorizer_bow.fit_transform(sentences)

# Convert the BOW representation to an array
bow_array_bigrams = X_bow.toarray()

# Get the feature names (unigrams and bigrams)
feature_names_bigrams = vectorizer_bow.get_feature_names_out()

# Display the results
print("Feature Names (Unigrams and Bigrams and Trigrams):")
print(feature_names_bigrams)
print("\nBag of Words Representation (Unigrams and Bigrams and Trigrams):")
print(bow_array_bigrams)


Feature Names (Unigrams and Bigrams and Trigrams):
['and' 'and dogs' 'and dogs are' 'animals' 'are' 'are great'
 'are great pets' 'are loyal' 'are loyal animals' 'at' 'at the'
 'at the cat' 'barked' 'barked at' 'barked at the' 'cat' 'cat sat'
 'cat sat on' 'cats' 'cats and' 'cats and dogs' 'dog' 'dog barked'
 'dog barked at' 'dogs' 'dogs are' 'dogs are great' 'dogs are loyal'
 'great' 'great pets' 'love' 'love my' 'love my cat' 'loyal'
 'loyal animals' 'mat' 'my' 'my cat' 'on' 'on the' 'on the mat' 'pets'
 'sat' 'sat on' 'sat on the' 'the' 'the cat' 'the cat sat' 'the dog'
 'the dog barked' 'the mat']

Bag of Words Representation (Unigrams and Bigrams and Trigrams):
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 1 1 1 0 1 1 1 2 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 2 1 0 1 1 0]
 [1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 

# TF-IDF of Unigrams + Bigrams 

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create a TfidfVectorizer instance for unigrams and bigrams
vectorizer_tfidf = TfidfVectorizer(ngram_range=(1, 2))

# Fit and transform the sentences to create the TF-IDF representation for unigrams and bigrams
X_tfidf = vectorizer_tfidf.fit_transform(sentences)

# Convert the TF-IDF representation to an array
tfidf_array_bigrams = X_tfidf.toarray()

# Get the feature names (unigrams and bigrams)
feature_names_tfidf_bigrams = vectorizer_tfidf.get_feature_names_out()

# Display the results
print("Feature Names (Unigrams and Bigrams):")
print(feature_names_tfidf_bigrams)
print("\nTF-IDF Representation (Unigrams and Bigrams):")
print(tfidf_array_bigrams)


Feature Names (Unigrams and Bigrams):
['and' 'and dogs' 'animals' 'are' 'are great' 'are loyal' 'at' 'at the'
 'barked' 'barked at' 'cat' 'cat sat' 'cats' 'cats and' 'dog' 'dog barked'
 'dogs' 'dogs are' 'great' 'great pets' 'love' 'love my' 'loyal'
 'loyal animals' 'mat' 'my' 'my cat' 'on' 'on the' 'pets' 'sat' 'sat on'
 'the' 'the cat' 'the dog' 'the mat']

TF-IDF Representation (Unigrams and Bigrams):
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.20470723 0.30566473
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.30566473 0.         0.         0.30566473 0.30566473 0.
  0.30566473 0.30566473 0.49321676 0.24660838 0.         0.30566473]
 [0.         0.         0.         0.         0.         0.
  0.30566473 0.30566473 0.30566473 0.30566473 0.20470723 0.
  0.         0.         0.30566473 0.30566473 0.         0.
  0.         0.         0.         

# build word2vec model using gensim 

In [8]:
import gensim
from gensim.models import Word2Vec

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Preprocess the sentences: tokenize and convert to lowercase
tokenized_sentences = [sentence.lower().split() for sentence in sentences]

# Build the Word2Vec model
model = Word2Vec(sentences=tokenized_sentences, vector_size=100, window=5, min_count=1, workers=4)

# Save the model
model.save("word2vec.model")

# Load the model (if needed)
# model = Word2Vec.load("word2vec.model")

# Example usage: Get the vector for a word
word_vector = model.wv['cat']
print("Vector for 'cat':")
print(word_vector)

# Example usage: Find similar words
similar_words = model.wv.most_similar('cat', topn=5)
print("\nMost similar words to 'cat':")
print(similar_words)


Vector for 'cat':
[-0.00714226  0.00124265 -0.00717659 -0.00224207  0.00371794  0.00583205
  0.00119609  0.00210415 -0.00411239  0.00722918 -0.00630918  0.00464433
 -0.00822246  0.00203907 -0.00497988 -0.00425001 -0.00311196  0.00565796
  0.0058002  -0.00497406  0.00077228 -0.00849441  0.00780826  0.00925741
 -0.00274478  0.00079992  0.00074601  0.00548158 -0.0086069   0.00058133
  0.00686806  0.00222932  0.00112576 -0.00931956  0.00848104 -0.00626174
 -0.00298954  0.00349149 -0.00077597  0.00141491  0.00178519 -0.00683123
 -0.0097282   0.00904432  0.00620004 -0.0069106   0.00340107  0.00020258
  0.00475476 -0.0071242   0.00402555  0.00434663  0.00996184 -0.00447107
 -0.00139039 -0.00731593 -0.00969583 -0.00908193 -0.00101934 -0.00650131
  0.00485089 -0.00616605  0.00251752  0.0007384  -0.00338965 -0.00098158
  0.009979    0.0091501  -0.00446099  0.00908617 -0.00564525  0.00593122
 -0.00309551  0.00343033  0.00302022  0.00690447 -0.00237422  0.0087751
  0.00758993 -0.00955069 -0.008012

# vector size 10 

In [9]:
import gensim
from gensim.models import Word2Vec

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Preprocess the sentences: tokenize and convert to lowercase
tokenized_sentences = [sentence.lower().split() for sentence in sentences]

# Build the Word2Vec model
model = Word2Vec(sentences=tokenized_sentences, vector_size=10, window=5, min_count=1, workers=4)

# Save the model
model.save("word2vec.model")

# Load the model (if needed)
# model = Word2Vec.load("word2vec.model")

# Example usage: Get the vector for a word
word_vector = model.wv['cat']
print("Vector for 'cat':")
print(word_vector)

# Example usage: Find similar words
similar_words = model.wv.most_similar('cat', topn=5)
print("\nMost similar words to 'cat':")
print(similar_words)


Vector for 'cat':
[-0.09601653  0.05004316 -0.08760495 -0.04390959 -0.00035496 -0.0029315
 -0.07658748  0.09618056  0.04982246  0.09236773]

Most similar words to 'cat':
[('on', 0.6144760847091675), ('i', 0.34242185950279236), ('sat', 0.24946902692317963), ('loyal', 0.14185985922813416), ('and', 0.11192134022712708)]


# build word2vec model using TF

In [10]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import skipgrams
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, Flatten

# Example sentences
sentences = [
    "The cat sat on the mat.",
    "The dog barked at the cat.",
    "Cats and dogs are great pets.",
    "I love my cat.",
    "Dogs are loyal animals."
]

# Preprocess the sentences: tokenize and convert to lowercase
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
total_words = len(tokenizer.word_index) + 1  # +1 for padding

# Create skip-grams
input_words, output_words = [], []
for sentence in sentences:
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    pairs, _ = skipgrams(tokenized_sentence, vocabulary_size=total_words, window_size=2, shuffle=True)
    input_words.extend([pair[0] for pair in pairs])
    output_words.extend([pair[1] for pair in pairs])

# Convert to numpy arrays
input_words = np.array(input_words)
output_words = np.array(output_words)

# Build the Word2Vec model
embedding_dim = 100
model = Sequential()
model.add(Embedding(input_dim=total_words, output_dim=embedding_dim, input_length=1, name='embedding_layer'))
model.add(Flatten())
model.add(Dense(total_words, activation='softmax'))

# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

# Train the model
model.fit(input_words, output_words, epochs=100, verbose=1)

# Example usage: Get the vector for a word
word_index = tokenizer.word_index['cat']
word_vector = model.layers[0].get_weights()[0][word_index]
print("Vector for 'cat':")
print(word_vector)

# Example usage: Find similar words
def find_similar_words(word, top_n=5):
    word_vector = model.layers[0].get_weights()[0][tokenizer.word_index[word]]
    similarities = {}
    for w, idx in tokenizer.word_index.items():
        if w != word:
            # use cosine instead of dot product 
            sim = np.dot(word_vector, model.layers[0].get_weights()[0][idx])
            similarities[w] = sim
    similar_words = sorted(similarities.items(), key=lambda x: x[1], reverse=True)[:top_n]
    return similar_words

similar_words = find_similar_words('cat')
print("\nMost similar words to 'cat':")
print(similar_words)


Epoch 1/100


/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2.9969
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9868 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9731 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9608 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9486 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9446 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9293 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9151 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9070 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8913 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8774 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8619 
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8537 
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8368 
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8158 
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━

# use Gensim pre-trained embedding models 

* https://github.com/piskvorky/gensim-data
* https://radimrehurek.com/gensim/models/word2vec.html

In [12]:
import gensim.downloader as api

# Download and load the pre-trained Word2Vec model
model = api.load("word2vec-google-news-300")

# Example usage: Get the vector for a word
word_vector = model['cat']
print("Vector for 'cat':")
print(word_vector)

# Example usage: Find similar words
similar_words = model.most_similar('cat', topn=5)
print("\nMost similar words to 'cat':")
print(similar_words)

# Example usage: Calculate similarity between two words
similarity = model.similarity('cat', 'dog')
print("\nSimilarity between 'cat' and 'dog':")
print(similarity)


[==================================================] 100.0% 1662.8/1662.8MB downloaded
Vector for 'cat':
[ 0.0123291   0.20410156 -0.28515625  0.21679688  0.11816406  0.08300781
  0.04980469 -0.00952148  0.22070312 -0.12597656  0.08056641 -0.5859375
 -0.00445557 -0.296875   -0.01312256 -0.08349609  0.05053711  0.15136719
 -0.44921875 -0.0135498   0.21484375 -0.14746094  0.22460938 -0.125
 -0.09716797  0.24902344 -0.2890625   0.36523438  0.41210938 -0.0859375
 -0.07861328 -0.19726562 -0.09082031 -0.14160156 -0.10253906  0.13085938
 -0.00346375  0.07226562  0.04418945  0.34570312  0.07470703 -0.11230469
  0.06738281  0.11230469  0.01977539 -0.12353516  0.20996094 -0.07226562
 -0.02783203  0.05541992 -0.33398438  0.08544922  0.34375     0.13964844
  0.04931641 -0.13476562  0.16308594 -0.37304688  0.39648438  0.10693359
  0.22167969  0.21289062 -0.08984375  0.20703125  0.08935547 -0.08251953
  0.05957031  0.10205078 -0.19238281 -0.09082031  0.4921875   0.03955078
 -0.07080078 -0.0019989  -

# GloVe pre-trained model 

In [13]:
import gensim.downloader as api

# Download and load the pre-trained gLoVe model
model = api.load("glove-twitter-25")

# Example usage: Get the vector for a word
word_vector = model['cat']
print("Vector for 'cat':")
print(word_vector)

# Example usage: Find similar words
similar_words = model.most_similar('cat', topn=5)
print("\nMost similar words to 'cat':")
print(similar_words)

# Example usage: Calculate similarity between two words
similarity = model.similarity('cat', 'dog')
print("\nSimilarity between 'cat' and 'dog':")
print(similarity)


[==================================================] 100.0% 104.8/104.8MB downloaded
Vector for 'cat':
[-0.96419  -0.60978   0.67449   0.35113   0.41317  -0.21241   1.3796
  0.12854   0.31567   0.66325   0.3391   -0.18934  -3.325    -1.1491
 -0.4129    0.2195    0.8706   -0.50616  -0.12781  -0.066965  0.065761
  0.43927   0.1758   -0.56058   0.13529 ]

Most similar words to 'cat':
[('dog', 0.9590820074081421), ('monkey', 0.920357882976532), ('bear', 0.9143136739730835), ('pet', 0.9108031392097473), ('girl', 0.8880629539489746)]

Similarity between 'cat' and 'dog':
0.95908207
